app:
  name: markex-api
  port: 4000
  env: dev
  prodMode: false

log:
  filepath: ./logs/app.log
  level: -1
  format: json

mongo:
  uri: eiei
  database: eiei

redis:
  host: redis-12048.c1.ap-southeast-1-1.ec2.redns.redis-cloud.com
  port: 12048
  password: eiei
  prefix: dev
  database: 0
